/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Button.vue')['default']
    ConfirmButton: typeof import('./src/components/ConfirmButton.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./src/components/Table.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
  }
}
