/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArrayEditor: typeof import('./src/components/JsonSchemaEditor/renderers/ArrayEditor.vue')['default']
    BlocklyEditor: typeof import('./src/components/BlocklyEditor/BlocklyEditor.vue')['default']
    BooleanEditor: typeof import('./src/components/JsonSchemaEditor/renderers/BooleanEditor.vue')['default']
    Breadcrumbs: typeof import('./src/components/Breadcrumbs.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Collapse: typeof import('./src/components/Collapse.vue')['default']
    ConfirmButton: typeof import('./src/components/ConfirmButton.vue')['default']
    Dialog: typeof import('./src/components/Dialog.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    Help: typeof import('./src/components/Help.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    IntelligentButton: typeof import('./src/components/IntelligentButton.vue')['default']
    JsonSchemaEditor: typeof import('./src/components/JsonSchemaEditor/JsonSchemaEditor.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    NullEditor: typeof import('./src/components/JsonSchemaEditor/renderers/NullEditor.vue')['default']
    NumberEditor: typeof import('./src/components/JsonSchemaEditor/renderers/NumberEditor.vue')['default']
    ObjectEditor: typeof import('./src/components/JsonSchemaEditor/renderers/ObjectEditor.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Radio: typeof import('./src/components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    StringEditor: typeof import('./src/components/JsonSchemaEditor/renderers/StringEditor.vue')['default']
    Swap: typeof import('./src/components/Swap.vue')['default']
    Switch: typeof import('./src/components/Switch.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    Toggle: typeof import('./src/components/Toggle.vue')['default']
    TypeSelect: typeof import('./src/components/JsonSchemaEditor/components/TypeSelect.vue')['default']
  }
}
